project_prompt = "Please check Claude.md for codebase rules and getting yourself oriented! To learn what MCP is, check out `library_docs/mcp/conceptual_overview.md`. DO NOT START WORKING UNTIL YOU UNDERSTAND WHAT THE MCP IS AND WHAT A MCP SERVER IS. READ THE README. READ THE PROJECT DETAILS."

test = ["./test.sh"]
lint = ["./lint.sh"]
