[project]
name = "canvas-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Darin Kishore", email = "darinkishore@protonmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
